package main

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
)

//Usage: go run generate_certificates.go <domain.name>
//domain.name will be created as a directory and files generated by generate_certificates.go will go into the directory with name "domain.name".
func main() {
	domainName := os.Args[1]

	//1)Ensure a directory named after the domain name passed in always exists
	_, err := os.Stat(domainName)
	if errors.Is(err, os.ErrNotExist) {
		//Create a new directory
		os.Mkdir(domainName, 0700)
	}

	//2)Create a root authority key for the domain, if it doesn't already exist
	//openssl genpkey -outform pem -out root.pem -algorithm rsa
	rootKeyOutputPath := fmt.Sprintf("%s/root.pem", domainName)
	//arguments := make([]string, 7)
	arguments := []string{"genpkey", "-outform", "pem", "-out", rootKeyOutputPath, "-algorithm", "rsa"}
	cmd := exec.Command("openssl", arguments...)

	if err := cmd.Run(); err != nil {
		fmt.Println("An error occurred when running openSSL")
		fmt.Println(err)
	}

}
